services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .volumes/data:/app/data
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./frontend:/usr/share/nginx/html

  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile
      args:
        TORCH_BACKEND: cpu
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .volumes/data:/app/inference/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432" # For local access
    volumes:
      - .volumes/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
