services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        TORCH_BACKEND: cpu
    expose:
      - "8000"
    environment:
      CAMERA_URL: http://192.168.0.104:2222/video

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
