services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        TORCH_BACKEND: cpu
    expose:
      - "8000"
    environment:
      CAMERA_URL: http://192.168.0.104:2222/video

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
