[project]
name = "mtg-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pillow>=12.1.0", "redis>=7.4.0", "tqdm>=4.67.1"]

[tool.ruff]
# Enable/disable rules
select = ["ALL"]
ignore = [
  "E501",
  "T201",
  "D103",
  "D107",
  "D100",
  "INP001",
] # Optional: Add rules to ignore, e.g., ["E501"]

# Line length
line-length = 120

# Target Python version
target-version = "py310"

# Exclude files or directories
exclude = ["__pycache__", ".git", ".venv", "venv", ".pytype", "build", "dist"]

# Show fixable count at the end
show-fixes = true

[dependency-groups]
dev = [
  "iprogress>=0.4",
  "ipykernel>=7.2.0",
  "ipywidgets>=8.1.8",
  "kaggle>=2.0.1",
  "matplotlib>=3.10.8",
  "matplotlib-inline>=0.2.1",
  "polars>=1.40.1",
]
inference = [
  "hnswlib>=0.8.0",
  "pydantic>=2.12.5",
  "transformers>=4.57.6",
  "opencv-python>=4.11.0.86",
  "numpy>=2.4.1",
]
backend = [
  "fastapi>=0.128.0",
  "uvicorn[standard]>=0.40.0",
  "python-multipart>=0.0.26",
  "sqlalchemy>=2.0.0",
  "psycopg[binary]>=3.1.0",
  "psycopg2-binary>=2.9.12",
  "opencv-python>=4.11.0.86",
  "numpy>=2.4.1",
]
parser = [
  "pandas>=2.3.3",
  "aiohttp>=3.9.0",
  "aiofiles>=23.2.1",
  "ijson>=3.2.3",
  "pyarrow>=15.0.0",
]
[project.optional-dependencies]
cpu = ["torch>=2.9.1"]
cu128 = ["torch>=2.9.1"]


[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cu128" }]]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
